version: "3.9"

services:
  ms-delivery-kotlin:
    container_name: ms-delivery-kotlin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-delivery-kotlin.rule=PathPrefix:(`/admin/api`)"
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
